title: Roya Sadeghimehr
logo: /assets/profile.jpg
description: Experienced Data Scientist Available from September 2024, Proficient in machine learning and data analytics with a versatile background spanning finance, energy, food industry, and logistics. Committed to delivering innovative and proactive solutions that drive business success in both independent and collaborative settings.
show_downloads: true
theme: jekyll-theme-minimal
